### ISSUE TITLE
NaN clock rate

### ISSUE THREAD

**Issue by emvolz** [theosanderson/chronumental#29]
For some small data sets with relatively narrow sampling ranges (in time) we are seeing that the clock rate fails to be estimated by RTT and no time trees are output. 
Specifying an initial clock rate resolves the issue. I suggest making an informative error message in this case and requesting the user to specif an initial rate.

**Comment by theosanderson** [comment]
Thanks for raising the issue. Your suggestions sound sensible A possible alternative fix would be to specify a lower learning rate with e.g. `--lr 0.005`

**Comment by theosanderson** [comment]
Oh sorry, I mis-read your issue. Will look into this.

**Comment by theosanderson** [comment]
Would it be at all possible to provide a dataset that suffers from this (email would be fine)? I can't see how scipy.stats.linregress can give NAs unless NAs are going into the input so my suspicion is that the problem is upstream of the RTT. (I still agree that there is a need to change Chronumental to avoid user confusion, whatever is causing this!)

**Comment by theosanderson** [comment]
@emvolz kindly provided the test files, this showed:

```
No clock rate specified, performing root-to-tip regression to estimate starting value
Root to tip regression: got rate of: -4.124466221643822
```

So now that makes sense, the RTT is producing a value but its a negative value, and that messes everything up. Added a message here as suggested: https://github.com/theosanderson/chronumental/commit/3c2f42412f19d344e53a78f753c499784e014fbe . Thanks so much for raising the issue.
